version: 0.0
os: linux
files:
  - source: app.rb
    destination: /home/ec2-user/
  - source: Gemfile
    destination: /home/ec2-user/
  - source: Gemfile.lock
    destination: /home/ec2-user/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/bundle_install
      timeout: 300
      runas: root
  ApplicationStop: 
    - location: scripts/stop_server.sh
      timeout: 30
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 30
      runas: root
