#!/bin/bash

cd /home/ec2-user
sudo yum update -y

# Installing ruby version 2.4
sudo yum install ruby24 -y
# Installing ruby development kit (needed to build gems)
sudo yum install ruby24-devel.x86_64 -y
# Installing c++ garbage collector (needed to build gems)
sudo yum install gcc-c++ -y

# Setting ruby version 2.4 as default
sudo alternatives --set ruby /usr/bin/ruby2.4
sudo gem2.4 install bundler --bindir /usr/bin
